spring:
  profiles: 
    active: dev
---
spring:
  profiles: test
    application:
      name: spring-cloud-config-test
---
spring:
  profiles: data
    application:
      name: spring-cloud-config-data
